/* tokens/*.css  ->  ios/Shared/Generated/DesignTokens.swift
 *
 * The design system and the app must not drift apart, so the CSS custom
 * properties stay the single source of truth and the Swift is generated.
 *
 * Deliberately dependency-free -- same reasoning as .design-sync/serve.mjs.
 * Run:  node tools/gen-tokens.mjs
 *
 * Only value shapes that map cleanly onto Swift are emitted:
 *   #hex / rgba()  -> Color        px -> CGFloat        s -> TimeInterval
 * Everything else (font stacks, cubic-bezier, shadow composites, deg) is
 * reported as skipped rather than guessed at.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(ROOT, 'ios', 'Shared', 'Generated', 'DesignTokens.swift');

/* file -> the Swift enum its tokens land in. The Swift *type* is decided per
   value, not per file: motion.css carries --arrive-rise in px alongside its
   durations, and classifying by filename would silently drop it. */
const GROUPS = [
  { file: 'colors.css',     enumName: 'Colors' },
  { file: 'spacing.css',    enumName: 'Spacing' },
  { file: 'radius.css',     enumName: 'Radius' },
  { file: 'motion.css',     enumName: 'Motion' },
  { file: 'typography.css', enumName: 'FontSize' },
  // elevation.css is intentionally absent: the system has almost no elevation,
  // and a CSS shadow composite has no faithful single-value Swift equivalent.
];

/* Only the first :root block per file. colors.css follows it with
   [data-theme="light"]/[dark], and motion.css with a reduced-motion :root --
   neither is the default theme, so neither belongs in the generated defaults. */
function firstRootBlock(css) {
  const i = css.indexOf(':root');
  if (i === -1) return '';
  const open = css.indexOf('{', i);
  if (open === -1) return '';
  let depth = 0;
  for (let j = open; j < css.length; j++) {
    if (css[j] === '{') depth++;
    else if (css[j] === '}' && --depth === 0) return css.slice(open + 1, j);
  }
  return '';
}

function parseDecls(block) {
  const out = new Map();
  // strip comments so a commented-out declaration cannot be picked up
  const clean = block.replace(/\/\*[\s\S]*?\*\//g, '');
  for (const line of clean.split(';')) {
    const m = line.match(/^\s*(--[A-Za-z0-9-]+)\s*:\s*([\s\S]+)$/);
    if (m) out.set(m[1], m[2].trim());
  }
  return out;
}

/* var(--a) chains resolve against every token seen, across files */
function resolve(value, all, seen = new Set()) {
  const m = value.match(/^var\(\s*(--[A-Za-z0-9-]+)\s*\)$/);
  if (!m) return value;
  const name = m[1];
  if (seen.has(name)) return value;      // cycle -- leave it, it will be skipped
  seen.add(name);
  const next = all.get(name);
  return next === undefined ? value : resolve(next, all, seen);
}

const swiftName = css =>
  css.replace(/^--/, '')
     .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const f = n => (Number.isInteger(n) ? `${n}` : `${n}`);

/* Classify by value shape. Returns { type, literal } or null to skip. */
function toSwift(raw) {
  const v = raw.trim();
  let m;

  if ((m = v.match(/^#([0-9a-fA-F]{6})$/)))
    return { type: 'Color', literal: `Color(hex: 0x${m[1].toUpperCase()})` };

  if ((m = v.match(/^#([0-9a-fA-F]{3})$/))) {
    const [r, g, b] = m[1].split('');
    return { type: 'Color', literal: `Color(hex: 0x${(r + r + g + g + b + b).toUpperCase()})` };
  }

  if ((m = v.match(/^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/))) {
    const [r, g, b] = [m[1], m[2], m[3]].map(n => (parseFloat(n) / 255).toFixed(4));
    const a = m[4] === undefined ? '1' : f(parseFloat(m[4]));
    return { type: 'Color', literal: `Color(red: ${r}, green: ${g}, blue: ${b}, opacity: ${a})` };
  }

  if ((m = v.match(/^(-?[\d.]+)px$/)))
    return { type: 'CGFloat', literal: f(parseFloat(m[1])) };

  if ((m = v.match(/^(-?[\d.]+)(ms|s)$/))) {
    const n = parseFloat(m[1]);
    return { type: 'TimeInterval', literal: f(m[2] === 'ms' ? n / 1000 : n) };
  }

  return null;
}

const HEADER = `// Generated by tools/gen-tokens.mjs from tokens/*.css -- do not edit by hand.
//
// Night is the default theme, so these are the night values. The light grove
// palette lives under [data-theme="light"] in tokens/colors.css and is the room
// around the device, not the product -- it is deliberately not generated here.

import SwiftUI

public enum DesignTokens {
`;

const FOOTER = `}

extension Color {
    /// 0xRRGGBB -- the form tokens/colors.css writes.
    init(hex: UInt32) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: 1
        )
    }
}
`;

async function main() {
  // one pass to collect every token, so var() can resolve across files
  const blocks = new Map();
  const all = new Map();
  for (const g of GROUPS) {
    const css = await readFile(join(ROOT, 'tokens', g.file), 'utf8');
    const decls = parseDecls(firstRootBlock(css));
    blocks.set(g.file, decls);
    for (const [k, v] of decls) if (!all.has(k)) all.set(k, v);
  }

  let body = '';
  const skipped = [];
  let emitted = 0;

  for (const g of GROUPS) {
    const lines = [];
    for (const [name, raw] of blocks.get(g.file)) {
      const swift = toSwift(resolve(raw, all));
      if (swift === null) { skipped.push(`${name} (${g.file})`); continue; }
      lines.push(`        public static let ${swiftName(name)}: ${swift.type} = ${swift.literal}`);
      emitted++;
    }
    if (!lines.length) continue;
    body += `    public enum ${g.enumName} {\n${lines.join('\n')}\n    }\n\n`;
  }

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, HEADER + body + FOOTER, 'utf8');

  console.log(`wrote ${OUT}`);
  console.log(`  ${emitted} tokens emitted, ${skipped.length} skipped`);
  if (skipped.length) console.log(`  skipped: ${skipped.join(', ')}`);
}

main().catch(e => { console.error(e); process.exit(1); });
